# Generated by Django 5.1.4 on 2025-08-18 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('representation', models.TextField(blank=True, null=True)),
                ('state', models.IntegerField(default=0)),
                ('role', models.CharField(choices=[('teenager', 'Teenager'), ('educator', 'Educator'), ('adult', 'Adult')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
