# Generated by Django 5.1.4 on 2025-08-21 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_customer_date_of_birth_customer_exciting_statement_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='joining_info',
            new_name='joining_again',
        ),
    ]
